---
abstract: 'Simple in-memory cache for AnyEvent applications'
author:
  - 'Daisuke (yet another) Maki <maki.daisuke@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-InMemoryCache
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  AnyEvent::InMemoryCache:
    file: lib/AnyEvent/InMemoryCache.pm
    version: 0.01
requires:
  AnyEvent: 0
  Time::Duration::Parse: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/Maki-Daisuke/p5-AnyEvent-InMemoryCache/issues
  homepage: https://github.com/Maki-Daisuke/p5-AnyEvent-InMemoryCache
  repository: https://github.com/Maki-Daisuke/p5-AnyEvent-InMemoryCache
version: 0.01
